name: ESP32 Firmware CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PlatformIO
        run: pip install platformio

      - name: Verify PlatformIO
        run: pio --version

      - name: Build Firmware
        run: pio run

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32-firmware
          path: |
            .pio/build/esp32dev/*.bin
