name: ESP32 Firmware Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build Firmware
        run: pio run

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            .pio/build/esp32dev/firmware.bin
            .pio/build/esp32dev/bootloader.bin
            .pio/build/esp32dev/partitions.bin
